export const PerformanceConfig = Object.freeze({
  BATCH_SIZE: 250,
  FRAME_BUDGET_MS: 10,
  MIN_CANVAS_HEIGHT: 240,
  MAX_CANVAS_HEIGHT: 1400,
  CANVAS_VERTICAL_PADDING: 130,
  RESIZE_DEBOUNCE_MS: 200,
});
